name: NuGet

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
        PACKAGESTOKEN:
          required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          submodules: 'true'
          fetch-depth: 0

    - id: nuget-push
      uses: ERNI-Academy/assets-github-actions-dotnet-nugetpush@v1
      with:
         pakages_token: ${{ secrets.PACKAGESTOKEN }}